# Generated by Django 3.1.3 on 2020-12-17 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeD', '0003_clients_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='password',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(flags=0, message='password must be at least 8 characters long with 1one or more numbers, uppercase letters, and special characters', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[#*&?!£$^@~|])[a-zA-Z\\d#*&?!£$^@~|]{8,}$')]),
        ),
    ]
